class_skl_logreg:
  trainFiles: 'gs://my_ml_test_bucket/sample_data/binary_classification_numeric_sample_data.csv'
  args:
    - 'C'
    - '1.5'
    - 'penalty'
    - 'l2'
class_askl:
  trainFiles: 'gs://my_ml_test_bucket/sample_data/binary_classification_numeric_sample_data.csv'
  args:
    - 'time_left_for_this_task'
    - '60'
    - 'ensemble_size'
    - '10'
    - 'ml_memory_limit'
    - '100'
class_lgbm:
  trainFiles: 'gs://my_ml_test_bucket/sample_data/binary_classification_numeric_sample_data.csv'
  args:
    - 'n_estimators'
    - '10'
    - 'max_depth'
    - '3'
class_xgb:
  trainFiles: 'gs://my_ml_test_bucket/sample_data/binary_classification_numeric_sample_data.csv'
  args:
    - 'n_estimators'
    - '10'
    - 'max_depth'
    - '3'
class_dummy:
  trainFiles: 'gs://my_ml_test_bucket/sample_data/binary_classification_numeric_sample_data.csv'
  args:
    - 'strategy'
    - 'prior'