class_skl_logreg:
  trainFiles: 'gs://my_customers_bucket/DUMMY/SAMPLES/TRAIN_DATA/MAIN/'
  modelFile: 'gs://my_core_model_bucket/dummy_samples_main_20190924152858_class_skl_logreg_basic/model_20190924_153035_DhRJx91rmM.pkl'
  scoreDir: 'gs://my_customers_bucket/DUMMY/SAMPLES/SCORE_DATA/MAIN/'
  outputDir: 'gs://my_data_staging_bucket/'
  useProba: '1'
  args:
    - 'C'
    - '1.5'
    - 'penalty'
    - 'l2'
class_askl:
  trainFiles: 'gs://my_customers_bucket/DUMMY/SAMPLES/TRAIN_DATA/MAIN/'
  args:
    - 'time_left_for_this_task'
    - '60'
    - 'ensemble_size'
    - '10'
    - 'ml_memory_limit'
    - '100'
class_lgbm:
  trainFiles: 'gs://my_customers_bucket/DUMMY/SAMPLES/TRAIN_DATA/MAIN/'
  args:
    - 'n_estimators'
    - '10'
    - 'max_depth'
    - '3'
class_xgb:
  trainFiles: 'gs://my_customers_bucket/DUMMY/SAMPLES/TRAIN_DATA/MAIN/'
  args:
    - 'n_estimators'
    - '10'
    - 'max_depth'
    - '3'
class_dummy:
  trainFiles: 'gs://my_customers_bucket/DUMMY/SAMPLES/TRAIN_DATA/MAIN/'
  args:
    - 'strategy'
    - 'prior'