class_skl_logreg:
  goal: MAXIMIZE
  hyperparameterMetricTag: "accuracy"
  maxTrials: 10
  maxParallelTrials: 2
  enableTrialEarlyStopping: True
  params:
    - parameterName: C
      type: DOUBLE
      minValue: 0.1
      maxValue: 10
    - parameterName: penalty
      type: CATEGORICAL
      categoricalValues: ["l2", "l1"]
class_xgb:
  goal: MAXIMIZE
  hyperparameterMetricTag: "accuracy"
  maxTrials: 10
  maxParallelTrials: 2
  enableTrialEarlyStopping: True
  params:
    - parameterName: n_estimators
      type: DOUBLE
      minValue: 10
      maxValue: 500
    - parameterName: max_depth
      type: DOUBLE
      minValue: 1
      maxValue: 20