class_skl_logreg:
  goal: MAXIMIZE
  hyperparameterMetricTag: "accuracy"
  maxTrials: 10
  maxParallelTrials: 2
  enableTrialEarlyStopping: True
  params:
    - parameterName: C
      type: DOUBLE
      minValue: 0.1
      maxValue: 10
      scaleType: "UNIT_LOG_SCALE"
    - parameterName: penalty
      type: CATEGORICAL
      categoricalValues: ["l2", "l1"]
class_xgb:
  goal: MAXIMIZE
  hyperparameterMetricTag: "accuracy"
  maxTrials: 10
  maxParallelTrials: 2
  enableTrialEarlyStopping: True
  params:
    - parameterName: n_estimators
      type: INTEGER
      minValue: 10
      maxValue: 500
    - parameterName: max_depth
      type: INTEGER
      minValue: 1
      maxValue: 10
class_lgbm:
  goal: MAXIMIZE
  hyperparameterMetricTag: "accuracy"
  maxTrials: 10
  maxParallelTrials: 2
  enableTrialEarlyStopping: True
  params:
    - parameterName: n_estimators
      type: INTEGER
      minValue: 10
      maxValue: 500
    - parameterName: max_depth
      type: INTEGER
      minValue: 1
      maxValue: 10
class_qda:
  goal: MAXIMIZE
  hyperparameterMetricTag: "accuracy"
  maxTrials: 10
  maxParallelTrials: 2
  enableTrialEarlyStopping: True
  params:
    - parameterName: reg-param
      type: DOUBLE
      minValue: 0
      maxValue: 1